vim.g.loaded_perl_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.loaded_ruby_provider = 0
vim.g.loaded_node_provider = 0
vim.g.loaded_python_provider = 0
vim.g.loaded_python3_provider = 0
vim.g.markdown_recommended_style = 0

vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 1
vim.opt.completeopt = { "menu", "menuone", "noselect", "noinsert" }
vim.opt.conceallevel = 3
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.foldenable = true
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.foldlevel = 1
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = "expr"
vim.opt.foldnestmax = 10
--vim.opt.formatoptions = "jcroqntp]"
vim.opt.guifont = "MonoLisa iamdb:h10"
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.laststatus = 3
vim.opt.list = true
vim.opt.mouse = "vi"
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.scrolloff = 20
vim.opt.sessionoptions = { "buffers", "curdir", "folds", "globals", "tabpages", "winpos", "winsize" }
vim.opt.shiftround = true
vim.opt.shiftwidth = 2
vim.opt.showmode = false
vim.opt.smartcase = true
vim.opt.softtabstop = 2
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.tabstop = 2
vim.opt.termguicolors = true
--vim.opt.textwidth = 120
vim.opt.ttyfast = true
vim.opt.undofile = true
vim.opt.updatetime = 200
--vim.opt.wrap = false
vim.wo.signcolumn = "yes:1"
